"""Calibration corpora and the importance matrices they produce.

An imatrix is one number per input feature of one weight matrix: the mean
squared activation that feature saw while the model read a calibration
corpus. The quantiser spends its limited bit budget where that number is
large. So the imatrix is a *summary of the calibration text*, and two corpora
that excite different features produce two different quantised models from
identical starting weights.

That is the mechanism this repository measures. Everything here exists to
make it observable: fixed corpora so the experiment is deterministic, a
forward hook to collect the statistic, and a cosine comparison so the
divergence between two calibration sets can be reported before any
perplexity is computed.

Corpora are vendored inline rather than downloaded. Three reasons, in order
of importance: the results file is regenerated by CI and byte-compared, so a
dataset that reorders or revises upstream would break the build; a fresh
clone must work offline; and a reader can see exactly what the model was
calibrated on without fetching anything. The cost is that these are small,
hand-assembled samples rather than corpus-scale text, which is stated plainly
in the Limitations section of the README.
"""

from __future__ import annotations

from dataclasses import dataclass

# --- the corpora ------------------------------------------------------

#: Wikipedia-style expository prose. The conventional imatrix corpus and the
#: closest thing to a default in the llama.cpp ecosystem.
_ENCYCLOPEDIC = """\
The Rhine is one of the major European rivers. It rises in the Swiss canton \
of Graubunden in the southeastern Swiss Alps, forms part of the Swiss-Austrian \
and Swiss-Liechtenstein borders, then flows in a mostly northerly direction \
through Germany and eventually empties into the North Sea in the Netherlands.
Photosynthesis is a process used by plants and other organisms to convert \
light energy into chemical energy that, through cellular respiration, can \
later be released to fuel the organism's activities. Some of this chemical \
energy is stored in carbohydrate molecules, such as sugars and starches, \
which are synthesised from carbon dioxide and water.
The Treaty of Westphalia refers to the two peace treaties signed in Osnabruck \
and Munster in 1648. They ended the Thirty Years' War in the Holy Roman Empire \
and the Eighty Years' War between Spain and the Dutch Republic. The treaties \
are often cited as the origin of the modern system of sovereign states.
Mitochondria are organelles found in the cells of most eukaryotes. They \
generate most of the chemical energy needed to power the cell's biochemical \
reactions. Chemical energy produced by the mitochondria is stored in a small \
molecule called adenosine triphosphate.
The Industrial Revolution was a period of global transition of human economy \
towards more efficient and stable manufacturing processes. It began in Great \
Britain and continued to spread through continental Europe and the United \
States during the period from around 1760 to about 1820.
Plate tectonics is the scientific theory that the Earth's lithosphere \
comprises a number of large tectonic plates which have been slowly moving \
since about three and a half billion years ago. The model builds on the \
concept of continental drift, an idea developed during the early twentieth \
century.
"""

#: Source code. A deliberately different token distribution: punctuation
#: density, identifier fragments, indentation, and almost no natural-language
#: function words.
_CODE = """\
def binary_search(items, target):
    lo, hi = 0, len(items) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        if items[mid] == target:
            return mid
        if items[mid] < target:
            lo = mid + 1
        else:
            hi = mid - 1
    return -1

class LRUCache:
    def __init__(self, capacity: int) -> None:
        self.capacity = capacity
        self._store: dict[int, int] = {}

    def get(self, key: int) -> int:
        if key not in self._store:
            return -1
        value = self._store.pop(key)
        self._store[key] = value
        return value

    def put(self, key: int, value: int) -> None:
        if key in self._store:
            self._store.pop(key)
        elif len(self._store) >= self.capacity:
            self._store.pop(next(iter(self._store)))
        self._store[key] = value

SELECT u.id, u.email, COUNT(o.id) AS order_count
FROM users AS u
LEFT JOIN orders AS o ON o.user_id = u.id
WHERE u.created_at >= '2024-01-01'
GROUP BY u.id, u.email
HAVING COUNT(o.id) > 3
ORDER BY order_count DESC
LIMIT 100;

const debounce = (fn, wait) => {
  let timer = null;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), wait);
  };
};

for i in range(len(matrix)):
    for j in range(i + 1, len(matrix)):
        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
"""

#: Conversational instruction-following turns. Short, second-person, heavy on
#: imperatives and chat scaffolding -- the distribution an instruct model
#: actually meets in deployment.
_CHAT = """\
User: Hey, can you help me write a short thank-you note to my landlord?
Assistant: Of course. Here is a draft you can adjust:
Dear Mr Alvarez, thank you for arranging the boiler repair so quickly last \
week. It made a real difference during the cold snap, and I appreciate you \
following up. Best regards, Sam.
User: That's great, thanks! Could you make it a bit less formal?
Assistant: Sure, here is a warmer version. Hi Mr Alvarez, just wanted to say \
thanks for sorting the boiler so fast last week. It really helped. Cheers, Sam.
User: What should I cook tonight? I have chicken thighs, rice and a lemon.
Assistant: A one-pan lemon chicken and rice works well with exactly those. \
Brown the thighs skin-side down, set them aside, toast the rice in the fat, \
add stock and lemon zest, put the chicken back on top, and bake it covered \
for about thirty minutes.
User: Do I need to soak the rice first?
Assistant: No, not for this. Soaking would make it too soft once it absorbs \
the stock. Just rinse it if you want to wash off the surface starch.
User: I'm nervous about a presentation tomorrow. Any advice?
Assistant: Rehearse only the opening two minutes until they are automatic. \
Most nerves peak at the start, and once you are past a beginning you know \
cold, the rest tends to follow. Also plan where you will pause.
User: Thanks, that actually helps a lot.
Assistant: Glad to hear it. Good luck tomorrow.
"""

#: The held-out evaluation text. Never used for calibration. Deliberately
#: encyclopedic, which means the ENCYCLOPEDIC corpus is the *matched* one and
#: CODE and CHAT are mismatched -- the asymmetry is the point of the
#: experiment, and stating it here keeps it from looking like an accident.
_EVAL = """\
The Antikythera mechanism is an ancient Greek hand-powered orrery, described \
as the oldest known example of an analogue computer. It was used to predict \
astronomical positions and eclipses decades in advance, and to track the \
four-year cycle of athletic games similar to an Olympiad.
Convection is single or multiphase fluid flow that occurs spontaneously \
through the combined effects of material property heterogeneity and body \
forces on a fluid, most commonly density and gravity. When the cause of the \
convection is unspecified, convection due to the effects of thermal expansion \
and buoyancy can be assumed.
The Bronze Age collapse was a time of widespread societal collapse during the \
twelfth century before the common era, associated with environmental change, \
mass migration, and the destruction of cities. It affected a large area of the \
Eastern Mediterranean and the Near East, and the palace economies of the \
Aegean and Anatolia gave way to isolated village cultures.
Enzymes are proteins that act as biological catalysts by accelerating chemical \
reactions. The molecules upon which enzymes may act are called substrates, and \
the enzyme converts the substrates into different molecules known as products. \
Almost all metabolic processes in the cell need enzyme catalysis in order to \
occur at rates fast enough to sustain life.
The Silk Road was a network of Eurasian trade routes active from the second \
century before the common era until the mid fifteenth century. Spanning over \
six thousand kilometres, it played a central role in facilitating economic, \
cultural, political and religious interactions between the East and West. \
Trade on the route was a significant factor in the development of the \
civilisations of China, Korea, Japan, India, Iran, Arabia and Europe.
Sedimentary rocks are types of rock formed by the cementation of mineral or \
organic particles at the Earth's surface, followed by compaction within bodies \
of water. Sedimentation is the collective name for processes that cause these \
particles to settle in place. The particles that form a sedimentary rock are \
called sediment, and may be composed of geological detritus or biological \
detritus.
The printing press is a mechanical device for applying pressure to an inked \
surface resting upon a medium, thereby transferring the ink. Johannes \
Gutenberg, a goldsmith by profession, developed a printing system by adapting \
existing technologies to printing purposes, as well as making inventions of \
his own. His newly devised hand mould made possible the precise and rapid \
creation of metal movable type in large quantities.
Ocean currents are continuous, directed movements of seawater generated by a \
number of forces acting upon the water, including wind, the Coriolis effect, \
breaking waves, temperature and salinity differences. Depth contours, shoreline \
configurations, and interactions with other currents influence a current's \
direction and strength. Ocean currents move both horizontally and vertically \
and occur on both local and global scales.
The Library of Alexandria was one of the largest and most significant \
libraries of the ancient world. It was dedicated to the Muses, the nine \
goddesses of the arts, and flourished under the patronage of the Ptolemaic \
dynasty. The library was part of a larger research institution, and many \
important scholars of the Hellenistic period worked there.
Immunity is the capacity of multicellular organisms to resist harmful \
microorganisms. Immunity involves both specific and nonspecific components. \
The nonspecific components act as barriers or eliminators of a wide range of \
pathogens irrespective of their antigenic make-up. Other components of the \
immune system adapt themselves to each new disease encountered and can \
generate pathogen-specific immunity.
Glaciers form where the accumulation of snow exceeds its ablation over many \
years, often centuries. They slowly deform and flow due to stresses induced \
by their weight, creating crevasses and other distinguishing features. They \
also abrade rock and debris from their substrate to create landforms such as \
cirques, moraines, and fjords.
Cartography is the study and practice of making and using maps. Combining \
science, aesthetics and technique, cartography builds on the premise that \
reality, or an imagined reality, can be modelled in ways that communicate \
spatial information effectively. The fundamental objectives of traditional \
cartography are to set the map's agenda and select the traits of the object \
to be mapped.
Volcanism is the phenomenon of eruption of molten rock onto the surface of a \
planet, where lava, pyroclastics and volcanic gases erupt through a break in \
the surface. It is caused by the presence of heat within the interior, and the \
process is a major mechanism by which planets lose their internal heat and by \
which secondary atmospheres are generated.
"""


@dataclass(frozen=True)
class Corpus:
    """A named block of calibration text.

    ``description`` is carried through to the results file so a reader can
    tell what distinction a spread number is actually measuring, rather than
    seeing two opaque labels.
    """

    name: str
    description: str
    text: str

    def __str__(self) -> str:  # pragma: no cover - trivial
        return self.name


CORPORA: tuple[Corpus, ...] = (
    Corpus("encyclopedic", "Wikipedia-style expository prose", _ENCYCLOPEDIC),
    Corpus("code", "Python, SQL and JavaScript source", _CODE),
    Corpus("chat", "Instruction-following dialogue turns", _CHAT),
)

CORPORA_BY_NAME: dict[str, Corpus] = {c.name: c for c in CORPORA}

EVAL_CORPUS = Corpus("held-out", "Encyclopedic prose, disjoint from all calibration sets", _EVAL)


# --- importance matrices ----------------------------------------------


def importance_from_activations(activations: list) -> dict:
    """Reduce collected activation batches to one importance vector per layer.

    The statistic is the mean of the squared activation over every token seen,
    per input feature. This is what llama.cpp's ``llama-imatrix`` computes,
    and the reason it is squared rather than absolute is that the quantiser
    minimises a squared reconstruction error -- the weight and the objective
    have to be in the same units or the weighting is arbitrary.

    ``activations`` is a list of ``(name, sum_sq, count)`` triples, summed
    across batches by the caller so nothing large is retained.
    """
    out: dict[str, object] = {}
    for name, sum_sq, count in activations:
        if count <= 0:
            raise ValueError(f"no tokens observed for {name}")
        out[name] = sum_sq / count
    return out


def cosine_similarity(a, b) -> float:
    """Cosine between two importance vectors.

    Reported instead of a raw distance because imatrix magnitude is arbitrary
    -- the quantiser only uses the vector's *shape*, since scaling every
    weight by the same constant cannot change which feature is relatively
    more important. Cosine is invariant to exactly that scaling, so it
    isolates the part of the difference that can actually affect the output.

    Returns a value in [-1, 1]; activation energies are non-negative so in
    practice it lands in [0, 1].
    """
    import numpy as np

    x = np.asarray(a, dtype=np.float64).ravel()
    y = np.asarray(b, dtype=np.float64).ravel()
    if x.shape != y.shape:
        raise ValueError(f"importance vectors differ in shape: {x.shape} vs {y.shape}")
    nx, ny = np.linalg.norm(x), np.linalg.norm(y)
    if nx == 0 or ny == 0:
        raise ValueError("cannot take cosine of a zero importance vector")
    return float(np.dot(x, y) / (nx * ny))
